<?php

return [
    'news_count' => 5,
    'search_count' => 18,
    'site_name' => 'JR東日本東北総合サービス株式会社【LiViT】',
    'template1_tag_priority' => ['カテゴリ', '目的', '駅', '県'],
    'template1_excluded_tag' => ['食べる', '買う', 'サービス', 'おすすめ品', 'ニュース・イベント', '求人情報'],
    'template1_num_images' => 3,
    'max_keywords_length' => 100,
    'static_tag_names' => [
        'news' => 'ニュース・イベント',
        'pivot' => 'Pivot',
        'pivot_magazine' => 'Pivotマガジン',
        'pivot_furukawa' => 'ピボット古川店',
        'pivot_koriyama' => 'ピボット郡山店',
        'pivot_aizu' => 'ピボット会津若松店',
        'pivot_fukushima' => 'ピボット福島店',
        'sendaist' => '仙台駅',
        'tekute' => 'tekute',
        'tekute_sendai' => 'tekuteせんだい',
        'tekute_nagamachi' => 'tekuteながまち',
        'tekute_tagajo' => 'tekuteたがじょう',
        'tekute_honshiogama' => 'tekuteほんしおがま',
        'yomu_tekute' => 'てくてNEWS',
        'ekito' => 'Ekito. Tagajo',
        'seagull' => 'シーガルタウン',
        'market' => '生鮮市場',
        'recruitment' => '求人情報',
        'tourism' => '観光',
        'shop' => 'お店',
        'product' => '商品',
        'information' => '情報',
        'detail' => 'さらに詳しく',
        'shop_list' => 'ショップ一覧',
    ],
    'tag_class_on_search_box' => [
        'くりこま高原駅' => 'sa4_2',
        'さくらんぼ東根駅' => 'sa5_3',
        'ニュース・イベント' => 'ac6',
        'かまぼこ・海産物' => 'ac15',
        'スイーツ・菓子' => 'ac16',
        '地域コラボ商品' => 'ac18',
        '食料品・日用品' => 'ac21',
    ],
    'item_class_on_search_box' => [
        'ニュース・イベント' => 'acnews',
    ],
    'company_page' => [
        'news_release_top_list_count' => 10,
        'news_release_list_count' => 10,
    ],
    'ellipsis_mode' => env('ELLIPSIS_MODE', 1),
];
